name: gustomaster
description: "Prueba Técnica Flutter - GustoMaster"

# La siguiente línea previene publicaciones accidentales en pub.dev.
publish_to: 'none' 

# La siguiente línea define la versión de la aplicación.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencias de la aplicación. Aquí se declaran los paquetes de los que depende el proyecto.
dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0

# Dependencias de desarrollo. Estos paquetes solo se usan en el entorno de desarrollo y pruebas.
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# La siguiente sección contiene configuraciones específicas para Flutter.
flutter:

  # La siguiente línea habilita el uso del conjunto de iconos de Material Design.
  uses-material-design: true

  # Declaración de recursos (assets).
  # Esta sección registra los archivos que se incluirán en el paquete de la aplicación.
  assets:
    # Registra todos los archivos contenidos en la carpeta 'assets/images/'.
    # La barra inclinada al final asegura que todos los elementos del directorio sean incluidos.
    - assets/images/